name: build_deploy

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      id: build
      run:  sh ./build.sh
    
    - uses: actions/upload-artifact@v4
      if: ${{ failure() && steps.build.outcome == 'failure' }}
      with:
        name: build-log
        path: |
          ./Vendor/*.log
          ./build/scratch*/*/ffmpeg/ffbuild/config.log
          ./build/scratch*/*/mpv/meson-logs/meson-log.txt
    
    - name: package
      run:  sh ./xcframework.sh

    - name: commit and push
      run: |
        git config --global user.name 'Fixfly'
        git config --global user.email 'fixfly-1010@fixfly.com'
        git add .
        git commit -m 'add build aritifacts'
        git push origin main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
